### ISSUE TITLE
发现有个人翻译到后面了

### ISSUE THREAD

**Issue by mooction** [racaljk/EffectiveModernCppChinese#3]
cnblog 上 boydfd 翻译到 Item27了，
http://www.cnblogs.com/boydfd/category/753605.html
不知道你们能否相互参考一下，哈哈

**Comment by racaljk** [comment]
嘿嘿，我太懒了，只能保证三年之内翻译+修订完。

这个算是个人兴趣，就没必要打扰博主啦

**Comment by SawaraNazo** [comment]
这本书好像已经完成翻译了欸，而且马上要出版了。（消息来自知乎

![screenshot-2017-12-19 effective modern c -](https://user-images.githubusercontent.com/31041465/34152231-d6daf93e-e4e8-11e7-8b74-ad97c63da53b.png)

**Comment by Devin-caofeng** [comment]
在网上看到消息说，这本书的中文版在今年3月份出版，是由高博翻译的，侯捷老师给写的序
